### ISSUE TITLE
Unsubscription

### ISSUE THREAD

**Issue by tyeety** [ng-web-apis/intersection-observer#9]
Currently, there is no way to unsubscribe or even disconnect observer in directive mode.
Sometimes we use intersection observer for lazy loading and it only needs to run code one time, otherwise it may have performance issues.
I suggest to add an option to disable or disconnect or reconnect after a while.

**Comment by MarsiBarsi** [comment]
Hey 👋  Thank you for the issue!
It is really an interesting architecture thing and we'll think about how to implement it :)

**Comment by waterplea** [comment]
Hi @tyeety ! I think we can expose waIntersectionObserver directive with `exportAs` and since it extends IntersectionObserver class you would be able to unobserve elements or stop observer completely. In the meantime, a tiny wrapper directive for observee is an option you can use:
https://stackblitz.com/edit/angular-single-intersection?file=src%2Fapp%2Ffirst-intersection%2Ffirst-intersection.directive.ts

**Comment by waterplea** [comment]
@tyeety I've added `exportAs` to the directive in `2.1.0`. Now you can use template reference variable to access observer:
```html
<div 
  #observer="IntersectonObserver"
  waIntersectionObserver
  (waIntersectionObservee)="onIntersection($event, observer)"
>
```
```typescript
onIntersection(entries, observer) {
  if (condition) {
    observer.disconnect();
  }
}
```

You can also `unobserver` particular elements if you run one observer per multiple elements.

**Comment by tyeety** [comment]
Thanks, @waterplea I tested it and it works as expected.
Again, Thank you 🌹
